### ISSUE TITLE
Angular 16 compatibility

### ISSUE THREAD

**Issue by lujakob** [hetznercloud/ngx-translate-mock#38]
This lib seems to be a deprecated View Engine lib. From Angular 16 on ngcc is not supported anymore and deprecated libs cannot be used. It would be great to be able to use this as an Ivy lib.

**Comment by wachri** [comment]
Thank you for opening this ticket 🙂.
We use this lib in our testing environment within an Angular 16 and have no problems. Have you tested it and you have had issues with it? Yes we are some version behind, since the lib is only used in our dev setup, we don't spend much effort on constantly updating it 🙈. But since we use it in a big Angular project where we are always pretty up-to-date, we notice (normally) relatively quickly when something breaks 🙂.

**Comment by lujakob** [comment]
Thx. I didn't try the upgrade yet, due to the information of version 16 not supporting View Engine libs and the terminal output indicating yours is one. But good to know, then I'll just try it, thanks.
